FROM openjdk:8-jdk

ENV PROJECT_DIR=/app

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY /notification/target/notification-2.2.1.RELEASE.jar   $PROJECT_DIR/notification.jar

CMD [ "java", "-jar", "notification.jar"]