FROM openjdk:8-jdk

ENV PROJECT_DIR=/app

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY /authentication/target/authentication-2.2.1.RELEASE.jar   $PROJECT_DIR/authentication.jar

CMD [ "java", "-jar", "authentication.jar"]