FROM openjdk:8-jdk

ENV PROJECT_DIR=/app

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY /catalog/target/catalog-2.2.1.RELEASE.jar   $PROJECT_DIR/catalog.jar

CMD [ "java", "-jar", "catalog.jar"]